version: '3.7'
services:
    teamchooser:
        image: abusyd1/teamchooser:testing
        build: ./
    db:
        image: mysql:8.0.19
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        environment:
            - MYSQL_DATABASE=example
            - MYSQL_ROOT_PASSWORD=password    