version: '3.7'
services:
    teamchooser:
        image: abusyd1/teamchooser:testing
        build: ./
    db:
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - "3307:3306"
        volumes:
          - ~/db/database.sql