version: '3.7'
services:
    teamchooser:
        image: abusyd1/teamchooser:testing
        build: ./
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql    
        restart: always
        environment:
            - MYSQL_DATABASE=example
            - MYSQL_ROOT_PASSWORD=password    